#!/bin/bash

# Test vdi repair functionality when inode object is broken

. ./common

for i in `seq 0 2`; do
    _start_sheep $i
done

_wait_for_sheep 3

$DOG node list

_cluster_format -i

$DOG vdi create test 12M
_vdi_list

echo "original data" | $DOG vdi write test

_random | dd of=$STORE/0/obj/807c2b2500000000 bs=4096 count=2048 &> /dev/null

$DOG cluster shutdown

for i in `seq 0 2`; do
    _start_sheep $i
done

_wait_for_sheep 3

$DOG vdi check test

$DOG vdi read test 0 14
